### ISSUE TITLE
why is my width and height the same

### ISSUE THREAD

**Issue by jimijon** [matiasgagliano/guillotine#24]
They are always 400 x 300?

I have spent too many hours and can't get this to work.
No matter what, even my demo, it always says 400x300.
Then there is a scale given that I can't figure out 0.472.
I can multiply it or divide any image width or length and it equals nothing that is relevant.

Please help me.

?

**Comment by Dargus77** [comment]
Same problem here since now.

This doesn't work:
picture.guillotine({eventOnChange: 'guillotinechange'})
picture.guillotine({width: 500, height: 500})

And this works for me:
picture.guillotine({width: 500, height: 500})
picture.guillotine({eventOnChange: 'guillotinechange'})

Is only a problem of order (at least in my case).

**Comment by matiasgagliano** [comment]
Please read the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) before posting. 

As mentioned there, if you found an issue provide the information needed to debug it, if you need assistance or have questions use one of the channels listed for those purposes.

Keep in mind that 400 by 300 px are the plugins **defaults**, if you want different dimensions you need to set them when initializing as in the example from the documentation.

**Comment by mikeyc7m** [comment]
I have this issue too, the reported size is always the initial width & height. I have wasted so much time failing to figure out the scaled width & height, not happy at all. How the fuck are we supposed to use this. Not happy. Could you please provide an example of how you magically produce the scaled width & height.

**Comment by matiasgagliano** [comment]
@mikeyc7m that doesn't deserve an answer. 

If you have questions start by reading the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md), and respect those taking the time to help you out.
