### ISSUE TITLE
Init Guillotine with preset x, y, zoom, scale & rotation

### ISSUE THREAD

**Issue by rnyberg** [matiasgagliano/guillotine#26]
I'm storing Guillotine data on saving a page, and would like to return it to previous state upon returning (we don't actually crop the image on an edit page, so that editors can easily finetune the image positions if they choose to edit an existing page).

Would be nice if Guillotine supported it's own getData object when initing.

For example like this:

	image.guillotine({
			w : 500,
			h : 400,
			x : 100,
            y : 50,
            angle : 0,
            scale: 1,
			eventOnChange: 'guillotinechange'
    });

Or simply image.guillotine({ data: dataobject, eventOnChange: 'guillotinechange' });

**Comment by matiasgagliano** [comment]
How is this different from the **init** option described in the [API](https://github.com/matiasgagliano/guillotine#api)?

**Comment by rnyberg** [comment]
I'm sorry, I read the README.md through a couple of times but evidently managed to skim over that option completely. :+1:

**Comment by matiasgagliano** [comment]
Not a problem, it happens. :+1:
