### ISSUE TITLE
Stop propagation in _start

### ISSUE THREAD

**Issue by Nelrohd** [matiasgagliano/guillotine#27]
Hi,

I was wondering why do you use "stopImmediatePropagation" in _start method?

Thank you

**Comment by matiasgagliano** [comment]
It's intended to keep the dragging process as fast as possible and to prevent future conflicts as the code base grows, but it should work just fine without it or with *stopPropagation*. Feel free to change it if you need to add event listeners or hooks.

**Comment by Nelrohd** [comment]
Thank you, it's what I did because I wanted to add the zoom support on mobile (two fingers). Are you still active on this repository btw?

**Comment by matiasgagliano** [comment]
Yes, I took some days to rest but I intend to keep on maintaining Guillotine.

**Comment by Nelrohd** [comment]
Oh ok perfect, I know it's not the best the topic for but what do you have in your backlog? Thank you

**Comment by matiasgagliano** [comment]
Personally I don't require any extra features for my implementations but the community appears to have given the plugin far more use cases than initially intended. I have some improvements noted in my TODO list to answer the more reasonable requests:

- Internalize the process of checking if the image is loaded and notify when the plugin is ready (throw event) to allow dynamically displaying the buttons, etc.
- Related to the previous one, allow to change the image *src* without re-initializing the plugin.
- Extend API with *setData*.
- Zoom with mouse wheel.

However, any feature (included the ones listed above) won't make it into the plugin if they turn out to be against the main goals of the plugin. They are being **lightweight** and to maintain a **general API** that allows developers to implement the specific features they might need.

**Comment by Nelrohd** [comment]
Thank you for the list. The zoom for mobile will be nice as well since the plugin does touch support.
Btw, when I was checking for an image cropping plugin, I didn't find one with a good UX that's why I took yours so I could do whatever I wanted with it. Thank you again

**Comment by matiasgagliano** [comment]
Closing it as the main subject is solved, but feel free to add comments or to reopen it if needed.
