### ISSUE TITLE
Canvas width set to 0%

### ISSUE THREAD

**Issue by Pran54** [matiasgagliano/guillotine#3]
I was using the guillotine plugin along with images that were received from a server using ajax and php. For some reason, on the initial load, the 'guillotine-canvas' has a width set to 0%. Upon reloading the page, though, the width is set to 100%.

Any ideas? Thanks in advance. Great plugin by the way!

**Comment by marcelgruber** [comment]
I was using this with a Knockout.js binding and was accidentally initializing it twice which also caused the width to be 0%, so be sure you're only initializing once!

**Comment by milindk** [comment]
I'm trying to use guillotine for the image drawn on canvas. In the demo application after applying the frame class to canvas where image is drawn guillotine fails to function. Any idea?

Thanks in advance.
