### ISSUE TITLE
Image Distortion

### ISSUE THREAD

**Issue by diogogomeswww** [matiasgagliano/guillotine#32]
Hi,

First of all: great plugin!

I've done a lot of testing and debugging but can't find the problem.

I'm creating and edit photo form.
The users uploads the photo and can edit the photo before submitting the form.

The problem is that my div class="guillotine-canvas" is allways set to a square dimension, and that causes the distortion on the image.

Am I doing something wrong?

The html generated after the guillotine modifications is:
```
<div class="guillotine-window" style="width: 100%; height: auto; padding-top: 150%;">
	<div class="guillotine-canvas" style="height: 100%; width: 150%; top: 0px; left: -25%;">
		<img id="" ...>
	</div>
</div>
```
Really appreciate your help,
Diogo Gomes

**Comment by diogogomeswww** [comment]
Hi again,

Fix my bug with your SO answer.

Thanks for the great plugin,

Cheers,
Diogo Gomes

**Comment by matiasgagliano** [comment]
I'm glad that you could figure it out, and thanks for the compliments!

For future reference please read the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md).

Happy coding!
