### ISSUE TITLE
picture.guillotine('remove') does not fully remove instance.

### ISSUE THREAD

**Issue by benjaminprojas** [matiasgagliano/guillotine#34]
I am trying to swap photos out on the fly, and when I use 'remove' and then instantiate a new instance, it does not work properly.  Do you have any suggestions for this?

**Comment by matiasgagliano** [comment]
This is my favourite kind of issue, those that fix themselves! xD

**Comment by benjaminprojas** [comment]
@matiasgagliano I just read your contributing file and figured this was the wrong place ;)
