### ISSUE TITLE
Allow Zoom Factor to be get/set to a precific value

### ISSUE THREAD

**Issue by OOPMan** [matiasgagliano/guillotine#4]
It would be very useful if you could do the following:

```
var guillotineImage = $("#guillotine-image"),
      currentZoom = guillotineImage.guillotine("getZoom");
guillotineImage.guillotine("setZoom", currentZoom * 0.5);
```

**Comment by DenisFernandes** [comment]
Hi, i'm trying to create a slider to control the zoom as @matiasgagliano mentioned before

How i can get the min scale of the current image to set as "min attr" on my range input?

So this way i'll be able to set my zoomFactor, right?
```javascript
jQuery("#zoomControl").on( "input", function() {
	picture.guillotine('instance')._zoom(parseFloat(jQuery( this ).val()));
});
```
