### ISSUE TITLE
Rotation of 5 degrees

### ISSUE THREAD

**Issue by Pesulap** [matiasgagliano/guillotine#41]
Hi
you do not have someone modified code that needs to be carried out by rotation of 5 degrees? I try it myself, but the picture is deformed. : / So only if someone has already been addressed.
thanks

**Comment by matiasgagliano** [comment]
Sorry @Pesulap, I don't know any working fork that allows angles other than 90°.

There's a [similar question](https://groups.google.com/forum/#!topic/jquery-guillotine/V6Z__HwOO_Y) on the forum with an explanation of why this isn't very feasible.
