### ISSUE TITLE
Two image selection make conflicts

### ISSUE THREAD

**Issue by lizy1630** [matiasgagliano/guillotine#42]
Hi, I tried in my webpages and find a conflict when doing more than one picture crop/rotation.
The first one on my page works out fine, but the second is not showing the picture at all after doing picture.guillotine({width:xx,height:xx,eventOnChange: 'xxx'}).
Then I traced back, it happens to be this line in your code.
line 172:
guillotine = canvas.wrap(guillotine).parent();

---

UPDATE
Sorry, just checked, it was something conflicts with my css.

**Comment by matiasgali** [comment]
@lizy1630, you might want to check out [this answer](https://stackoverflow.com/questions/27380545/jquery-guillotine-swap-image#27408843) too.
