### ISSUE TITLE
When I click on the zoom the page scroll to the top

### ISSUE THREAD

**Issue by qawsedstation** [matiasgagliano/guillotine#44]
When I click on the zoom the page scroll to the top. 
If the page is scrolled down. When I press zoom or something else from the controls the page this scroll me up to the top of the page. Any quick fix?

**Comment by matiasgali** [comment]
Hi @qawsedstation, it doesn't appear to be an issue of the plugin itself but just in case if you provide a [JsFiddle](https://jsfiddle.net) or any kind of example I'll take a look at it.

**Comment by qawsedstation** [comment]
Fix it. Finally was a problem with the demo using the a href # this make
the page to go to the top I fix it by using a letter after the hash for
example #a

Thanks for the response good work!
George

**Comment by matiasgali** [comment]
I'm trying the [demo](guillotine.js.org) but I can't replicate the issue. 

The demo even calls `event.preventDefault()` [here](https://github.com/matiasgagliano/guillotine/blob/gh-pages/js/demo.js#L27) for the controls, so the links shouldn't trigger any actions.

Could you tell me what browser are you using?

**Comment by qawsedstation** [comment]
I test it me too. I get the code from the demo but should effect with
something in my code. Should work fine in the demo but react with something
else. and Because of the # go to the top of the page. Anyway I fix it just
putting #a on the href.

Thanks

2015-08-19 22:44 GMT+01:00 Matías Gagliano notifications@github.com:
