### ISSUE TITLE
Restrict to vertical dragging

### ISSUE THREAD

**Issue by hchor** [matiasgagliano/guillotine#46]
Maybe I missed this: is there a way to restrict the user so they can only drag the image up and down (vertically) and not horizontally? I display my image at 100% width so allowing them to drag it left and right can cause the image to cut off.

**Comment by matiasgali** [comment]
@hchor if you set the `width` option to be equal to the width of the image and the `height` option to be less than the height of the image then it will only allow vertical dragging.

If you have questions or need help please read the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md). Let's keep the issue tracker just to report issues.
