### ISSUE TITLE
how could i get the cropped image?

### ISSUE THREAD

**Issue by malkyg** [matiasgagliano/guillotine#49]
hi, 
how can i get the cropped image as base64 after the user is done with the editing?

**Comment by matiasgali** [comment]
Hi @malkyg, let's keep the issue tracker strictly to report issues/bugs. For questions refer to the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md).

The same question has been asked and answered in [Gitter's chat room](https://gitter.im/matiasgagliano/guillotine).
