### ISSUE TITLE
Zoom Step changes when Img src changes

### ISSUE THREAD

**Issue by Pran54** [matiasgagliano/guillotine#5]
Again, great plugin! I am using the guillotine plugin on an img tag with an src that changes (the src is based on an ajax request that is dynamically changed by a user). After changing the src multiple times, the zoomStep changes significantly. I tried hardcoding in the zoomStep when initializing the plugin, but this still didn't fix the issue.

Another thing that could be related is that I only set up the plugin once, on the original img tag, and never again even after the src changes. I could post some code if that helps.

**Comment by huynhgiatien** [comment]
hi all, i am having same problem with events get executed many times. Could you please help to let me know how exactly did you fix it?
"on each successful Ajax request remove the old instance, change the src and get a new Guillotine instance." => this is a solution, right? If so please help to let me know the detail steps. Thanks very much guys!

**Comment by huynhgiatien** [comment]
hi all, i am having same problem with events get executed many times. Could you please help to let me know how exactly did you fix it?
"on each successful Ajax request remove the old instance, change the src and get a new Guillotine instance." => this is a solution, right? If so please help to let me know the detail steps. Thanks very much guys!

**Comment by YuriGor** [comment]
Hi, try to call
````javascript
image.guillotine('remove');
````
and than init plugin again.

**Comment by huynhgiatien** [comment]
hi YuriGor, thanks very much for your quick response!
Unfortunately it seems does not work. My situation is: i open a picture, zoom it, drag it a bit then after that every events from zoom, rotate.... will be duplicated. Note that even zoom then if i do not drag the plugin still works fine.
Somehow zoom + drag causes my problem.
Could you please help! Thanks man.

var picture = $('#image_review');
picture.guillotine({width:300, height:300, eventOnChange: 'guillotinechange'});
        $('#rotate_left').click(function(){ picture.guillotine('rotateLeft'); });
        $('#rotate_right').click(function(){ picture.guillotine('rotateRight'); });
........

**Comment by YuriGor** [comment]
My current code looks like this:
````javascript
				$('#image_review').load(function () {//each time when image is loaded
					$(this).guillotine('remove');//clear previous instance, if it does exists
					$(this).guillotine({width: 300, height: 300,//setup new plugin instance
						onChange: function(data, action){
							alert('!');//this alert pops up only once on each change, even after image reload
						}});
				});
````
And it works fine.

**Comment by matiasgagliano** [comment]
@huynhgiatien please read the [CONTRIBUTING file](//github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) before posting.

The issue tracker is meant to be a record of bugs and problems of the repo itself. If it's poluted with questions, answers and comments it makes it harder to track the real issues and fix them.

So, as stated in *CONTRIBUTING*, **don't post questions** here. If you need help use on of the alternatives listed there for such purpose.

**Comment by huynhgiatien** [comment]
hi YuriGor, it works!! Thanks very much man. You save my day!
Sorry for adding comments the wrong way.
Again, such a great plugin and thanks all you guys for your help!
