### ISSUE TITLE
Controls bar doesnt appear ...

### ISSUE THREAD

**Issue by JPBigot** [matiasgagliano/guillotine#50]
Hi Matias, 

I've just downloaded and installed last guillotine version.

In my original html page : 
&nbsp;&nbsp;&nbsp;&nbsp;<div id="container-edit-image" style="width: 80%;"><img id="edited-image" src=" ........... " /></div>

and in my javascript :  
&nbsp;&nbsp;&nbsp;&nbsp;var picture = jQuery('#edited-image'); 
&nbsp;&nbsp;&nbsp;&nbsp;picture.guillotine({width: 400, height: 300}) ;
&nbsp;&nbsp;&nbsp;&nbsp;jQuery('#rotate-left-button').click(function(){ picture.guillotine('rotateLeft'); });
&nbsp;&nbsp;&nbsp;&nbsp;jQuery('#zoom-in-button').click(function(){ picture.guillotine('zoomIn'); });

When I run my page, the picture appears in the right frame (400x300), and I can deplace it. 
The original HTML has been transformed as : 
&nbsp;&nbsp;&nbsp;&nbsp;<div id="container-edit-image" style="width: 80%;" >
&nbsp;&nbsp;&nbsp;&nbsp;<div style="width: 100%; height: auto; padding-top: 75%;" class="guillotine-window">
&nbsp;&nbsp;&nbsp;&nbsp;<div style="width: 247.25%; height: 239.333%; top: -50.44%; left: -39.52%;" class="guillotine-canvas">
&nbsp;&nbsp;&nbsp;&nbsp;<img style="transform: perspective(1000px); backface-visibility: hidden;" id="edited-image" src=" ....................">
&nbsp&nbsp&nbsp&nbsp;</div></div></div>

And, I see that all javascript instructions are well executed, with break points in the mozilla debugger.

------>But the Guillotine controls bar doesnt appear !!
(jQueryguillotine.js is the 1.8.0)

What I did wrong ??

Thanks in advance

JPB

**Comment by rochapablo** [comment]
The controllers must be add into your HTML. See the source http://guillotine.js.org/.

**Comment by matiasgali** [comment]
@JPBigot, take a look at the demo that comes with the source, in the [index.html](https://github.com/matiasgagliano/guillotine/blob/master/demo/index.html#L22) file you'll see  that controls are added manually so you can customize them to whatever you need.

For future reference please read the [CONTRIBUTING](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) file, you'll find other resources more appropriate to get help and ask questions.

**Comment by JPBigot** [comment]
Hi Matias and Pablo,

I'm sorry, I thought that div control was create by guillotine.js ... 

Your plugin is great..!

Thx a lot

JPB
