### ISSUE TITLE
No way to restrict/warn for upscaling image pixels

### ISSUE THREAD

**Issue by Luke-SF** [matiasgagliano/guillotine#51]
Guillotine by default lets you zoom in so far that the scale is >1. That forces Imagemagick or whatever you use to scale it, to basically upscale pixels that don't exist, making it at least a little pixellated. (WP image editor doesn't even let you upscale with the ->resize() command, giving "Could not calculate resized image dimensions".)

Can we have an option to show a warning or not permit scale >1 ?

**Comment by matiasgali** [comment]
You can easily prevent scale from being greater than 1 from the handler you bind to the zoom in button.

``` javascript
$('#zoom-in-button').click(function(){
  if (picture.guillotine('getData')['scale'] * 1.1 > 1) return;
  picture.guillotine('zoomIn');
});
```
