### ISSUE TITLE
Transparent part of image looks white

### ISSUE THREAD

**Issue by Luke-SF** [matiasgagliano/guillotine#52]
Guillotine crop works great but it would be useful to have a checkered background in cases the image you're cropping has transparency!

**Comment by matiasgali** [comment]
That's very subjective and out of Guillotine's scope. Some might want a background, some might not. Using a bit of CSS it's very easy to set whatever background you want.

Guillotine aims to [do one thing and do it well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well), and that's to provide a good and simple API to get the cropping area from an image. For the rest Guillotine gets out of the way allowing developers to apply whatever design they want, manage data however they want and control what end-users can or can't do as they see fit.

In the [CONTRIBUTING file](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) there are few resources, like the chat, where it might be easier to propose and discuss possible new features.
