### ISSUE TITLE
Outline the full cropping range

### ISSUE THREAD

**Issue by garygreen** [matiasgagliano/guillotine#55]
It would be nice if when you are cropping / moving the image, it would outline the full cropping range of the image (maybe with a border or something) that way you can easily see how much you can more the image around by, and know where abouts you are on the image.

**Comment by matiasgali** [comment]
Hi @garygreen, it might be nice in some cases but it'd break most layouts.

Keep in mind that Guillotine is mostly a general API, try using the API and playing with the `.guillotine-window` and `.guillotine-canvas` CSS classes to get around and adapt it to your particular case.

Sorry for not being more helpful but it falls outside the purpose of the plugin.
