### ISSUE TITLE
How can I use the plugin with Aurelia?

### ISSUE THREAD

**Issue by felipesantanadev** [matiasgagliano/guillotine#59]
I'm using the Aurelia framework and would like to know how could I use Guillotine with it.

**Comment by matiasgali** [comment]
Hi @itsfelipesan, please take a look at the [CONTRIBUTING](https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md) file. Let's keep the issue tracker just to report bugs or issues, for help and questions you can refer to any of the resources listed there.

I haven't worked with Aurelia by maybe the community can help you.
