### ISSUE TITLE
Add support to change data via an API method

### ISSUE THREAD

**Issue by rmaceissoft** [matiasgagliano/guillotine#6]
would be nice if I could change x, y, scale and angle programmatically. For instance:

```
picture.guillotine('setData', { scale: 1.4, angle: 270, x: 10, y: 20 });
```

**Comment by YuriGor** [comment]
Hello, i am trying to align image to the top after calling 'fit' method.
````javascript
$(this).guillotine({width: 300, height: 300});
$(this).guillotine('fit');
$(this).guillotine({init:{y:0}});
````
But it doesn't work.

My aim is to crop photo to square avatar, and face on photo is on top part of image in most of cases, there is no sense to place stomach on avatar.

I suppose 'init' option works only at initial stage of creating preview,
so here is my use case, where this enhancement will be useful.
If there is any other way to achieve my goal - i will be happy to know it.

**Comment by matiasgagliano** [comment]
Options are only passed on initialization, and *init* is specifically meant to set the initial state.

For now you can achieve your goal using private methods as explained above.

I'll keep it in mind for future iterations.

**Comment by burakkilic** [comment]
@rmaceissoft , have you released angular.js version?

**Comment by YuriGor** [comment]
little fix for zero data values (f.e. { y: 0 }):
````javascript
// Helper to set data
var setData = function(gllt, data) {
  var current = gllt.getData(),
      factor  = (data.scale===undefined?current.scale:data.scale) / current.scale,
      angle   = (data.angle===undefined?current.angle:data.angle) - current.angle,
      left    = (data.x===undefined?current.x:data.x) / current.w,
      top     = (data.y===undefined?current.y:data.y) / current.h;
...
````
