### ISSUE TITLE
Fit to both dimensions

### ISSUE THREAD

**Issue by forcenine** [matiasgagliano/guillotine#63]
Is there anyway to make the fit() method resize the image within the canvas so that is fits within both the width and height?

For example, if the width is set to 640px and the height to 360px then I want the fit() method to resize the image until both dimensions are met - not just the width.

Is this possible?

**Comment by matiasgali** [comment]
Hi @forcenine, please take a look at the [CONTRIBUTING][1] file.

There you'll find a few better resources where you can post questions or ask for help so we can keep this issue tracker only to report actual bugs or issues.

The plugin is meant to get a portion of an image *without blank spaces* (no area without image) so when it fits it shrinks the image until one of its dimensions (width or height) is equal to the same dimension in the window (or guillotine).

The only way you can fit both width and height is if the image and window have the same aspect ratio.

[1]: https://github.com/matiasgagliano/guillotine/blob/master/CONTRIBUTING.md
